// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-44cV02QxZZALTm1sm8O5KJTtdlU10nk',
    appId: '1:451452787943:web:5892807e8832b3afb35642',
    messagingSenderId: '451452787943',
    projectId: 'task-manag-3871b',
    authDomain: 'task-manag-3871b.firebaseapp.com',
    storageBucket: 'task-manag-3871b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoFFk1nPRywqYNC4izl1-F8ZQdE34WDo',
    appId: '1:451452787943:android:6636851b4b50742ab35642',
    messagingSenderId: '451452787943',
    projectId: 'task-manag-3871b',
    storageBucket: 'task-manag-3871b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4wI7550P6EW3eN2q5DQcO74BUHOTiIcM',
    appId: '1:451452787943:ios:c2d9dd3d248e9a39b35642',
    messagingSenderId: '451452787943',
    projectId: 'task-manag-3871b',
    storageBucket: 'task-manag-3871b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4wI7550P6EW3eN2q5DQcO74BUHOTiIcM',
    appId: '1:451452787943:ios:c2d9dd3d248e9a39b35642',
    messagingSenderId: '451452787943',
    projectId: 'task-manag-3871b',
    storageBucket: 'task-manag-3871b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-44cV02QxZZALTm1sm8O5KJTtdlU10nk',
    appId: '1:451452787943:web:f5181fcfc41054deb35642',
    messagingSenderId: '451452787943',
    projectId: 'task-manag-3871b',
    authDomain: 'task-manag-3871b.firebaseapp.com',
    storageBucket: 'task-manag-3871b.firebasestorage.app',
  );
}
